# Docker compose file to build up the entier project
version: "0.1"

services:

  # Backend service to run the backend server
  backend:
    container_name: API-Builder-backend
    image: api-builder-api:latest
    command: python manage.py /backend/API/migrate --run-syncdb && python /backend/API/manage.py runserver 0.0.0.0:8000
    volumes:
      - /backend
    ports:
      - "8000:8000"

  #Frontend service to run the UI
  frontend:
    container_name: API-Builder-frontend
    image: api-builder-ui:latest
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0